import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider, ClerkLoaded, ClerkLoading } from '@clerk/nextjs'
import Navbar from './components/Navbar'
import Box from '@mui/material/Box'
import LinearProgress from '@mui/material/LinearProgress'

import { dark } from '@clerk/themes'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Clerk auth demo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en">
        <body className={inter.className}>
          <ClerkLoading>
            <div className="flex items-center justify-center h-screen text-2xl">
              <Box sx={{ width: '80%' }}>
                <LinearProgress />
              </Box>
            </div>
          </ClerkLoading>
          <ClerkLoaded>
            <div className="max-w-6xl mx-auto">
              <div className="flex flex-col h-screen">
                <Navbar />
                {children}
              </div>
            </div>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  )
}
